# Spring application configuration
spring:
  application:
    name: task-management-system
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: Syvaolento
  expiration: 3600000
logging:
  level:
    root: INFO
    org.springframework: DEBUG
  file:
    name: logs/application.log
server:
  port: 8080
  servlet:
    context-path: /api/v1
cache:
  type: none
